name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Env
        run: |
          echo NODE_VERSION=$(cat .tool-versions | sed -e "s/nodejs //g") >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install packages
        run: npm ci
      - name: Run Jest
        run: npm test
